version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - docker login -u AWS -p eyJwYXlsb2FkIjoiaXoyNnptQm5JUnJLOHdDRCthNXN3b2l5UmNyNWVkTFNkNldzYVY2YzJYZEFyOGY0dEtxRmMxQVNJTjhYTFpXMHk2cE9SVjdVdkZXdFJIbEw1Z28vbFJGN2pmeU1ZSUFDTUh4VG1rUE8vWkVqaGtqdGNBdFVZVFJZTVVTbjlmMG5SUXI3OTFBcXpPU2dpZVJYSTRIMmdkRVFEdjg2UmI3Ti9SeVhNVjh3d3dQTUkxeEtrOVJmNHJ5QzdmOS9xTTZQclhZMnFxTTJ4ZkdmZkliQ1RvV0VZZVhtRFR6RElnZkVsQlVsM3J2bWNCdkg4UUpwdHZpVzFubTBuRElVVVpYaUtMQk5iVjNwNjlKVWRHcWJUUkJib3Y4bStIMmttV2l6QmlBVkpLSUw2QjR5SllFNFNVcGtWdGd1RjdFa21zeHIwK3VRVWRYaE9oTUFRQzMrNk1hQThmM1NqOHlra0FPbmM4QTV2bmtWS2FtZ21NR1U4YVJ1SXFFM0kyc2hCY0tSbTlsbkdnRmNjeVh3eFpBTktQdXYwZ3I5cFFnNlE5dURqREpXMkhxYWZ6NVRWcFlSSmEwOTZlZ0ZPRWYwZHIzV0taa0dNeWVQODNpODB5a1BQazZBNGM3c1hoUno0aEdpSVZOTkVqQVRZSC80S21YdVVDREVmRmM5byt1LzczMjNoR0tVcWg0cWlpQS9uOFN6LzlXRGNsWUVZVUJ3QW4wNGFsdTR5Y2ZwbmxyMVdQR1p0UmpFUEdkc3NOWlBzSXdwdGhxMVVwR2lYK2IrSjlmdVJSQThKTkZqbUc4S1ZNQlNjc3dMUXRaNE1lZ2pCdFFKZENsZVptbm5GM0MvODI3SzdaOHVpWjFUdElvVTYxeXZPRWJ3NVB0RzI1bk1uczNzN3B3c3VYeHpaT3NaMXlVN3BrRlIxR0FET0p0TFVVK0MwTmFKbURxYzVKSDNlcUxjUTdWcHR3MTUvL3pBUk54QWROQjc3ak1ydTFJQjRBT0pIdnd0aUVXVzFiZnhmTlhpdlZiZVFTTHVEOFFBNU5BdThBR0NtV0VZTHBoMi9qM3FYTUNFZHNRV2Y4RXhiSjF2N3JkYlM0K0RYMjduVWRaMGpIT3RlVkc5UHM5MEV1dzNLSi8rcnhTdnNCakE4U2RrM1pvdi9mUGtkS0p1a01SY3BxSmlMdHpWZ01jL1dQamtjazgveHZKdGc3ZGZGQWxPT2RiNFhOSkdYMC92aEtaSFE5clJYcTl0c21vTWFaOEFnMzBsRksvZmFoSXpTU0JRV0JLVWJCeWJ5MzdKbDhUNXVFV3VObkloek5FU1crcnNFaU1nK3JxaVhwMXVYYTB1RW5RL1dCeTE2SlZ5M08zLzhNUDQ5a29raTRQVDFiZzZEcXkvRjhjR1o2SG1tVFR5YkdqcFhocHlsRHZKSExvNW5POCsyNUhNM1lSWHZBSktRaXh6MUlXNCIsImRhdGFrZXkiOiJBUUVCQUhod20wWWFJU0plUnRKbTVuMUc2dXFlZWtYdW9YWFBlNVVGY2U5UnE4LzE0d0FBQUg0d2ZBWUpLb1pJaHZjTkFRY0dvRzh3YlFJQkFEQm9CZ2txaGtpRzl3MEJCd0V3SGdZSllJWklBV1VEQkFFdU1CRUVERS9MUG1FbHBueVNmSy83T0FJQkVJQTd3RXJScDFZaHNRMEtvQ0Racjg0bCtiUFAwajBvYURVMzI4VlBPbHQwd2RqQ2xub0xzTWxZemoyK29HSk5jZTRRVGZ4OGVkcG9oZzJ3RXgwPSIsInZlcnNpb24iOiIyIiwidHlwZSI6IkRBVEFfS0VZIiwiZXhwaXJhdGlvbiI6MTU2NjE5MTM4Mn0= https://955334841448.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t capst-ecrdo-dgo85dzlowio .
      - docker tag capst-ecrdo-dgo85dzlowio:latest 955334841448.dkr.ecr.us-east-1.amazonaws.com/capst-ecrdo-dgo85dzlowio:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 955334841448.dkr.ecr.us-east-1.amazonaws.com/capst-ecrdo-dgo85dzlowio:latest
